classdef OFDMPreambleBuilder < handle
    properties
        params
        preambleOFDMMod
    end
    
    methods
        function obj = OFDMPreambleBuilder(params)
            obj.params = params;
            
            obj.preambleOFDMMod = comm.OFDMModulator( ...
                'FFTLength',            params.FFTLength, ...
                'NumGuardBandCarriers', params.NumGuardBandCarriers, ...
                'CyclicPrefixLength',   0);
        end
        
        function lstf = generateLSTF(obj)
            shortPreamble = ...
                [ 0    0  1+1i 0  0    0 -1-1i 0  0    0 ...
                1+1i 0  0    0 -1-1i 0  0    0 -1-1i 0 0 0 1+1i 0 0 0 ...
                0    0  0    0 -1-1i 0  0    0 -1-1i 0 0 0 1+1i 0 0 0 ...
                1+1i 0  0    0  1+1i 0  0    0  1+1i 0 0 ].';
            
            lstf = sqrt(13/6) * obj.preambleOFDMMod(shortPreamble);
        end
        
        function lltf = generateLLTF(obj)
            longPreamble = complex(...
                [ 1,  1, -1, -1,  1,  1, -1,  1, -1,  1,  1,  1,...
                1,  1,  1, -1, -1,  1,  1, -1,  1, -1,  1,  1,  1,  1, 0,...
                1, -1, -1,  1,  1, -1,  1, -1,  1, -1, -1, -1, -1, -1,...
                1,  1, -1, -1,  1, -1,  1, -1,  1,  1,  1,  1].', 0);
            
            lltf = obj.preambleOFDMMod(longPreamble);
        end
        
        function preamble = generatePreamble(obj)
            
            lstf = obj.generateLSTF();
            lltf = obj.generateLLTF();
            
            preamble = [ lstf; ...
                         lstf; ...
                         lstf(1:end/2); ...
                         lltf(end/2+1:end); ...
                         lltf; ...
                         lltf ];
        end
    end
    
    methods (Static)

        function lltfFreq = generateLLTFFreq()

        lltfFreq = complex([ ...
             1,  1, -1, -1,  1,  1, -1,  1, -1,  1,  1,  1,...
             1,  1,  1, -1, -1,  1,  1, -1,  1, -1,  1,  1,  1,  1, 0,...
             1, -1, -1,  1,  1, -1,  1, -1,  1, -1, -1, -1, -1, -1,...
             1,  1, -1, -1,  1, -1,  1, -1,  1,  1,  1,  1 ].', 0);
        end
    end
end
